### ISSUE TITLE
Allow inheriting default location from parent page/field

### ISSUE THREAD

**Issue by AugustMiller** [AugustMiller/kirby-map-field#12]
This will be super useful for clusters of points—say you have a series of events, and you want to add nearby locations: the user shouldn't be expected to pan the map from the default location over and over.

The search bar mitigates this problem, but for scenarios where address-search isn't possible, zooming and panning can get very laborious.

**Comment by AugustMiller** [comment]
Possible syntax:

```yml
fields:
  location:
    label: Location
    type: map
    center: inherit
```

…this means that we could dynamically change the default center of the map by updating the location of a parent page.
