### ISSUE TITLE
Access data in Structure format

### ISSUE THREAD

**Issue by jklue** [AugustMiller/kirby-map-field#15]
I would like to use this field in a Kirby structure field, but can't figure out how to access the data. Here's the page info:
````
----

Locations: 

-
  location: |
    address: Oakland, California
    lat: "37.8043637"
    lng: "-122.2711137"
    zoom: "9"
````

To access the first one entry in this structure, I'm trying `$page->locations()->toStructure()->first()->yaml()['lat']` but am getting a `Cannot use object of type Field as array` error. I've tried several variations but can't figure it out.
