### ISSUE TITLE
Location data not saved and fatal error on 

### ISSUE THREAD

**Issue by yvesio** [AugustMiller/kirby-map-field#2]
Dear August,

I actually encountered a strange problem regarding your kirby-map-field plugin. I think I've setup everything correctly:
- created a map folder within the plugin folder and copied all plugin content into it
- got a browser api key from google
- set the global defaults in config.php
- added the map field to my blueprint

So when I go to the page in the panel where I added the map field, I see everything like in your screenshot. I then lookup a location and hit save. When I leave the edit page in the panel, go somewhere else and then go back to the just edited page I get the following error:

```
Fatal error: Uncaught Error: Method name must be a string in /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/src/panel/models/page/changes.php:71 Stack trace:
#0 /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/forms/pages/edit.php(23): Kirby\Panel\Models\Page\Changes->differ()
#1 /home/www/sites/194.245.150.77/site/yves_io/dev/kirby/toolkit/helpers.php(270): Kirby\Panel->{closure}(Object(Kirby\Panel\Models\Page))
#2 /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/src/panel.php(315): call(Object(Closure), Array)
#3 /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/src/panel/models/page.php(135): Kirby\Panel->form('pages/edit', Object(Kirby\Panel\Models\Page), Object(Closure))
#4 /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/controllers/pages.php(68): Kirby\Panel\Models\Page->form('edit', Object(Closure))
#5 /home/www/sites/194.245.150.77/site/yves_io/dev/kirby/toolkit/helpers.php(270): PagesController->edit('_locations/pure...')
#6 /home/www/sites/194.245.150.77/site/yves_i in /home/www/sites/194.245.150.77/site/yves_io/dev/panel/app/src/panel/models/page/changes.php on line 71
```

I've looked at the page’s txt file and nothing regarding the map field is saved. When I go back from the error message, stroll around in the panel and visit the edited page, the same error occurs. When I logout of Kirby, re-login and visit the edited page I don't get the error message. Until I hit save again.

Kirby, the Toolkit, and the Panel are on 2.3.2. If I can give you any additional information, just let me know. 

If this sounds more like a Kirby issue I could post something on the Kirby forum.

Many thanks for your help,
Yves

**Comment by AugustMiller** [comment]
Updated your post to format the stack trace a bit better… At first glance, it doesn't look like this passes through any Map plugin code.

Do you mind posting the content of your blueprint?

I haven't encountered this error, nor explored the offending `Changes` class, before. I'd like to try and reproduce it locally!

**Comment by yvesio** [comment]
Sure, here is the blueprint’s content:

```
<?php if(!defined('KIRBY')) exit ?>

title: Link
files: true
fields:
  title: 
    label: Title
    type:  text
  address: 
    label: Address
    type:  text
  link: 
    label: Link
    type:  Url
  location
    label: Location
    type: map
```

Here the config.php content related to the plugin:

```
c::set('map.defaults.lat', 51.2107281);
c::set('map.defaults.lng', 6.764620100000002);
c::set('map.defaults.zoom', 9);
c::set('map.key', 'proper_key_removed');
```

**Comment by AugustMiller** [comment]
This may be as simple as the missing colon after `location` in your blueprint.

Otherwise, this looks fine.

Can you confirm that the blueprint above reflects your local file, and if so, that adding the colon (like below) fixes it?

``` yml
title: Link
files: true
fields:
  title: 
    label: Title
    type:  text
  address: 
    label: Address
    type:  text
  link: 
    label: Link
    type:  Url
  location: # <- Right here :)
    label: Location
    type: map
```

_Edit: I can reproduce the non-saving behavior with the missing colon, but I don't get the stack trace, even with `c::set('debug', true);`_
